# Generated by Django 5.1.3 on 2024-11-11 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('usuario', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('compania', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('usuario', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Domiciliario',
            fields=[
                ('cedula', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=50)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domiciliarios', to='app_core.administrador')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_entrega', models.CharField(max_length=255)),
                ('direccion_salida', models.CharField(max_length=255)),
                ('precio', models.FloatField()),
                ('distancia', models.FloatField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='app_core.cliente')),
                ('domiciliario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='app_core.domiciliario')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('placa', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('color', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=50)),
                ('domiciliario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='app_core.domiciliario')),
            ],
        ),
    ]
