# Generated by Django 5.1.3 on 2024-11-11 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='app_core.cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='distancia',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='domiciliario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='app_core.domiciliario'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='precio',
            field=models.FloatField(null=True),
        ),
    ]
