# Generated by Django 5.1.3 on 2024-11-12 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0002_alter_pedido_cliente_alter_pedido_distancia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(blank=True, default='Pendiente', max_length=100),
        ),
    ]
